#!/usr/bin/env bash

ROOTDIR=`pwd`
DEPSDIR=$ROOTDIR/deps

. util/ver.cfg

if [ ! -d $DEPSDIR ]; then
    mkdir $DEPSDIR
fi

cd $DEPSDIR

get() {
    tarname=$1-$2.tar.gz
    url=$3
    if [ ! -s $tarname ]; then
        wget --no-check-certificate $url -O $tarname || exit 1
        if [ $? == 0 ]; then
            tar -xzf $tarname || exit 1
            echo -e "GET "$tarname" [\033[0;32;40mOK\033[0m]\n"
        fi
    fi
}

get janus-gateway $V_JANUS_GATEWAY https://github.com/meetecho/janus-gateway/archive/$V_JANUS_GATEWAY.tar.gz || exit 1
get jansson $V_JANSSON https://github.com/akheron/jansson/archive/$V_JANSSON.tar.gz || exit 1
get glib $V_GLIB https://github.com/GNOME/glib/archive/$V_GLIB.tar.gz || exit 1

cd .. || exit 1
